# Generated by Django 4.1.5 on 2023-01-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_purchase_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='Descripción', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
