# Generated by Django 4.1.5 on 2023-01-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_providers_delete_purchase_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
