# Generated by Django 4.1.5 on 2023-01-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_providers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images'),
        ),
    ]
